### ISSUE TITLE
[IDEA] Agregar Celuzador

### ISSUE THREAD

**Issue by Theblood** [diegoespindola/osintChile#10]
Celuzador es capaz de traer el nombre y la foto de perfil de whatsapp como tambien el estado del mismo 

dejo un repositorio con codigo en python3 que consume una api: 
https://github.com/Theblood/Celuzador

Tambien dejo un sitio que esta abierto a consultas: 
https://celuzador.online/

**Comment by AlexisPradoLucero** [comment]
Acabo de hacer un fork ya lo he agregado deberia funcionar bien https://github.com/AlexisPradoLucero/osintChile

**Comment by Theblood** [comment]
Perfecto muchas gracias @AlexisPradoLucero !, ya pue @diegoespindola  cuando cuando ?

**Comment by diegoespindola** [comment]
ya ya

**Comment by diegoespindola** [comment]
merge ok, se cierra el ticket

**Comment by diegoespindola** [comment]
Muchas gracias por el aporte muchachos

**Comment by danieldumma** [comment]
Ya no vale la pena esta fuente a buscar otra
