### ISSUE TITLE
¿Cómo hacer la consulta si termina en -K?

### ISSUE THREAD

**Issue by KrlitosForever** [diegoespindola/osintChile#2]
Estimado junto con saludar y además de felicitarlo por tu iniciativa, te quería consultar por los rut terminados en -K.
Se deben remplazar por "cero" o por "uno" o esta en materia de investigación.

ya que al consultar un rut terminado en "K" me arroja error en SII.

```
  File "OSINTchile.py", line 23, in <module>
    sii.busqueda(rut = parametros.rut)
  File "/home/user/Desktop/Pruebas/osintChile/sources/sii.py", line 11, in busqueda
    busquedaRutSii(rut)
  File "/home/user/Desktop/Pruebas/osintChile/sources/sii.py", line 45, in busquedaRutSii
    print('     Rut                      :', divs[7].get_text())
IndexError: list index out of range
```

Ante cualquier aclaración se agradece la información.

Saludos.

**Comment by diegoespindola** [comment]
Hola, gracias por tu comentario, hasta ahora no me había pasado, me puedes enviar el RUT a diego@counterwise.cl para hacer pruebas y corregirlo porfa

**Comment by KrlitosForever** [comment]
Gracias por la pronta respuesta, me di cuenta que si ingresas el rut con "k" (en minúscula) arroja el error expuesto en el comentario anterior. Sin embargo si ingresas el rut con "K" (en mayúscula) no da el problema. Al igual que si ingresas erróneamente un rut da como el error del comentario anterior.
Te enviaré un correo a la brevedad.
Saludos.

**Comment by diegoespindola** [comment]
Corregido, disculpa la demora.
