### ISSUE TITLE
Sugerencia agregar mas fuentes

### ISSUE THREAD

**Issue by xhush** [diegoespindola/osintChile#3]
Me gustaria que se agregaran mas fuentes de informacion

**Comment by diegoespindola** [comment]
Hola, gracias por tu sugerencia.
Que fuente te gustaría agregar?

**Comment by xhush** [comment]
Esta https://www.spensiones.cl/apps/certificados/formConsultaAfiliacion.php

**Comment by diegoespindola** [comment]
Hola,
 por ahora no agregaremos fuentes con captcha.

**Comment by diegoespindola** [comment]
nofuentes con  captchas por ahora

**Comment by diegoespindola** [comment]
por ahora no agregaremos fuentes con captcha

**Comment by diegoespindola** [comment]
por ahora no agregaremos fuentes con captcha
