### ISSUE TITLE
¿Es posible agregar esta fuente?

### ISSUE THREAD

**Issue by MiClobiMC** [diegoespindola/osintChile#4]

**Comment by MiClobiMC** [comment]
https://masterchileapk.info/ws-patentes-v2/controller/scrapPatentes.php?key=acea298aa9699e635f5d7092ace832e2&opcion=buscarAuto&txtPatenteAuto=

esta es para las patentes por si deseas agregarla

**Comment by diegoespindola** [comment]
Gracias, Muy buenas fuentes, La agregaremos en cuanto tengamos menos carga de trabajo.

**Comment by MiClobiMC** [comment]
> Gracias, Muy buenas fuentes, La agregaremos en cuanto tengamos menos carga de trabajo.

Las envie al correo mejor las borre de aqui para evitar que otra persona lo haga primero

**Comment by MiClobiMC** [comment]
Creo que me equivoque de correo

**Comment by diegoespindola** [comment]
listo
