### ISSUE TITLE
Me da error en kali linux 2022

### ISSUE THREAD

**Issue by danieldumma** [diegoespindola/osintChile#7]
Parece que la ultima version de python da error esto me aparece
![error](https://user-images.githubusercontent.com/109353448/179219076-11b11421-6ae7-4c66-acee-ace6d7e5ea48.PNG)

**Comment by danieldumma** [comment]
Ya lo he solcuionado he tenido que reinstalar kali linux funciona pero el rutificador dice error 403 request eso no lo entiendo

**Comment by diegoespindola** [comment]
el error 403 es porque nombrerutyfirma cambio su pagina.
proxima version sera corregido
