### ISSUE TITLE
Ya no funciona para mostrar la edad ahora dire por que

### ISSUE THREAD

**Issue by danieldumma** [diegoespindola/osintChile#8]
La persona de masterapkchile hizo una actualizacion ahora la api es post esta es ahora https://epr.appmovil.org/edad-ws/endpoint si miras la api que estaba antes https://masterchileapk.info/ws-birthdayv3/api/?rut=5.126.663-3 te dice que la actualizo y tiene un mensaje ofensivo bueno aqui la obtuve la nueva api post
![2c02eb6a-86fa-4705-82d1-7bf77562093b](https://user-images.githubusercontent.com/109353448/184517161-5d0687ea-52e4-4521-a41c-67d60bdaaa8f.jpg)
![ff96420f-c66d-42c2-988e-72dfaa1570f4](https://user-images.githubusercontent.com/109353448/184517163-6c074f5e-9ef2-481f-acb8-20a8597cceb7.jpg)
![0da923cd-2153-40bd-8724-3f0b0c4b6c22](https://user-images.githubusercontent.com/109353448/184517164-39760f57-ac58-44d1-8d6e-e3089f3cec54.jpg)
![d361c963-6b7f-49da-8b9c-c508adf16bd0](https://user-images.githubusercontent.com/109353448/184517165-8f298f14-d7ba-46c1-ba7e-07d1eeb2312e.jpg)
![3d535ad3-b28e-464d-b457-541a4e03f648](https://user-images.githubusercontent.com/109353448/184517166-38845a5f-8d38-4a39-af92-5f7ef1b9f94c.jpg)
![3b936ea1-3746-4478-a136-372ce2aa8c56](https://user-images.githubusercontent.com/109353448/184517167-1430ca09-46dc-4575-a1ed-77ded2e0f262.jpg)
![a5f3bcbe-7da0-4ce6-9c02-32cca25f0033](https://user-images.githubusercontent.com/109353448/184517169-df39a77c-e99f-4315-9831-6e23f0fc0181.jpg)

**Comment by AlexisPradoLucero** [comment]
Hola no se si aun sigas interesado en esto pero agregue un calculador de edad aproximada en nombrerutyfirma lamentablemente no hay manera de acceder a la api de edad por rut el creador de la api puso seguridad para que no la usen gratis ya que monetiza en la playstore ese masterapkchile yo tratare de buscar api que cumplan con la misma funcion por el momento conformate con el calculo aproximado que hace en nombrerutyfirma

**Comment by danieldumma** [comment]
Porfin alguien me responde ya me habia cansado de esperar estuve viendo el repositorio y no esta lo que tu dices

**Comment by AlexisPradoLucero** [comment]
Hice este fork que viene con los nuevos cambios ya hice el pull requests solo toca esperar ver que dice @diegoespindola aqui te lo dejo https://github.com/AlexisPradoLucero/osintChile

**Comment by diegoespindola** [comment]
OSINTChile ya esta actualizado a la nueva version de la api muchas gracias @danieldumma  por la espera
